# Generated by Django 4.1.3 on 2022-11-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_stafforder_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stafforder',
            old_name='roomOrder_id',
            new_name='roomOrder',
        ),
        migrations.RenameField(
            model_name='stafforder',
            old_name='user_id',
            new_name='user',
        ),
    ]
