# Generated by Django 4.1.3 on 2022-11-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.TextField()),
                ('full_name', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
